### ISSUE TITLE
Entity Descriptions leaks into Field's description

### ISSUE THREAD

**Issue by d34dman** [factorial-io/phab-entity-scaffolder#20]
Example config,
```yaml
label: Foo
id: foo
description: "This description will be applied to field too"
fields:
  title:
    type: string
    label: Title
    description: ""
```
As in the above config, if field title's description is left empty, it gets picked up from Entity's description.
